sonar.projectKey=davidpro08_2026_1_OOAD
sonar.organization=davidpro08

sonar.sourceEncoding=UTF-8
sonar.sources=2026_1_OOAD
sonar.tests=tests
sonar.exclusions=build/**,**/CMakeFiles/**,**/googletest/**,2026_1_OOAD/Simulator/SystemTestMode.cpp
sonar.test.inclusions=tests/**/*.cpp
sonar.cfamily.compile-commands=build/compile_commands.json
sonar.coverageReportPaths=coverage.xml
sonar.coverage.inclusions=2026_1_OOAD/Class/**
sonar.coverage.exclusions=tests/**/*.cpp,2026_1_OOAD/main.cpp

sonar.qualitygate.wait=false
