sonar.projectKey=davidpro08_2026_1_OOAD
sonar.organization=davidpro08

sonar.sourceEncoding=UTF-8
sonar.sources=2026_1_OOAD
sonar.tests=tests
sonar.exclusions=build/**,**/CMakeFiles/**,**/googletest/**
sonar.test.inclusions=tests/**/*.cpp
sonar.coverage.exclusions=2026_1_OOAD/**,tests/**/*.cpp

sonar.qualitygate.wait=false