sonar.projectKey=davidpro08_2026_1_OOAD
sonar.organization=davidpro08

sonar.sourceEncoding=UTF-8
sonar.sources=2026_1_OOAD
sonar.tests=tests
sonar.exclusions=build/**,**/CMakeFiles/**,**/googletest/**
sonar.test.inclusions=tests/**/*.cpp
sonar.coverage.exclusions=tests/**/*.cpp,2026_1_OOAD/HDWARE/**,2026_1_OOAD/Simulator/**

sonar.qualitygate.wait=false