//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : IPower.h
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#if !defined(_IPOWER_H)
#define _IPOWER_H


class IPower {
public:
	virtual ~IPower() = default;
	virtual void turnOff() = 0;
};

#endif  //_IPOWER_H
