//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : MotorController.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//
#include "MotorController.h"
#include "SensorController.h"
#include "HDWARE/Motor.h"

MotorController::MotorController(EventBus* bus, Motor& motor)
    : bus(bus), motor(motor), isTurnOn(false) {

    bus->subScribeStartCleaning([this]() {
        this->turnOn();
    });
    bus->subScribeAvoidObstacle([this](SensorProvider* sensor) {
        this->AvoidObstacle(*sensor);
    });
}

void MotorController::turnOn() {
    isTurnOn = true;
    avoiding = false;
}

void MotorController::turnOff() {
    isTurnOn = false;
    avoiding = false;
    mySensor = nullptr;
}

void MotorController::AvoidObstacle(SensorProvider& provider) {
    mySensor = &provider;
    if(isTurnOn == false) {
        return;
	}

    if (afterTurnRight == true) {
        MCTurnLeft();
        avoiding = true;
        afterTurnRight = false;
    }
    else if (provider.getLeftState() == true) {
        MCTurnRight();
        afterTurnRight = true;
    }else{
        MCTurnLeft();
        avoiding = false;
    }
}
void MotorController::MCStop() {
    motor.stop();
}

void MotorController::MCMove() {
    if(isTurnOn == false) {
        return;
    }

    if(avoiding == false) {
        bus->publishStartCleaning();
        motor.moveForward();
    }else{
        MCMoveBackward();
        if (mySensor != nullptr) {
            bus->publishAvoidObstacle(mySensor);
        }
    }
}

void MotorController::MCTurnLeft() {
    motor.turnLeft();
}

void MotorController::MCTurnRight() {
    motor.turnRight();
}

void MotorController::MCMoveBackward() {
    motor.moveBackward();
}

bool MotorController::isAvoiding() const {
    return avoiding;
}
