//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : MotorController.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#include "Motor.h"

void Motor::stop() {

}

void Motor::moveForward() {
    point.x = point.x + direction.x;
    point.y = point.y + direction.y;

}

void Motor::turnLeft() {
    Point temp = direction;
    direction.x = -temp.y;
    direction.y = temp.x;

}

void Motor::turnRight() {
    Point temp = direction;
    direction.x = temp.y;
    direction.y = -temp.x;

}

void Motor::moveBackward() {
    point.x = point.x - direction.x;
    point.y = point.y - direction.y;

}