//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : MotorController.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#include "Motor.h"

void Motor::stop() {
    // Motor.stop()
}

void Motor::moveForward() {
    // Motor.moveForward()
}

void Motor::turnLeft() {
    // Motor.turnLeft()
}

void Motor::turnRight() {
    // Motor.turnRight()
} 

void Motor::moveBackward() {
    // Motor.moveBackward()
}