//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : MotorController.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#include "MotorController.h"
#include "SensorController.h"
#include "Motor.h"

MotorController::MotorController(EventBus* bus, Motor& motor)
    : bus(bus), motor(motor), isTurnOn(false) {

    bus->subScribeMoveForward([this]() {
        this->MCMoveForward();
    });
    bus->subScribeAvoidObstacle([this](SensorController* sensor) {
        this->AvoidObstacle(*sensor);
    });
}

void MotorController::turnOn() {
    isTurnOn = true;
}

void MotorController::turnOff() {
    isTurnOn = false;
}

void MotorController::AvoidObstacle(SensorProvider& provider) {
    if(isTurnOn == false) {
        return;
	}

    // 모터 멈춤
    MCStop();

    // SensorProvider mySensor 인터페이스를 사용해서 왼쪽 오른쪽 상태 받아오기
    if(provider.getRightState() == false) {
        MCTurnRight();
    }else if(provider.getLeftState() == false){
        MCTurnLeft();
    }else{
        int retry_limit = 100; 
        MCMoveBackward();
        while (provider.getLeftState() && provider.getRightState() && --retry_limit > 0) {
            MCMoveBackward();
        }
        if(provider.getRightState() == false) {
            MCTurnRight();
        }else if(provider.getLeftState() == false){
            MCTurnLeft();
        }
    }

    bus->publishMoveForward();
}

void MotorController::MCStop() {
    motor.stop();
}

void MotorController::MCMoveForward() {
    motor.moveForward();
}

void MotorController::MCTurnLeft() {
    motor.turnLeft();
}

void MotorController::MCTurnRight() {
    motor.turnRight();
}

void MotorController::MCMoveBackward() {
    motor.moveBackward();
}

