//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : PowerController.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#include "PowerController.h"

PowerController::PowerController(EventBus *bus)
{
    this->bus = bus;
}

void PowerController::turnOn()
{
    power = true;
    bus->publishMoveForward();
}

void PowerController::turnOff() {
    power = false;
    bus->publishTurnOff();
}

