//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : SensorController.h
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#if !defined(_SENSORCONTROLLER_H)
#define _SENSORCONTROLLER_H

#include "SensorProvider.h"
#include "IPower.h"
#include "EventBus.h"

class SensorController : public SensorProvider, public IPower {
public:
	SensorController(EventBus* bus);
	void turnOn();
	void turnOff() override;
	void FrontObstacleDetected();
	bool getLeftState();
	bool getRightState();
	void ChecknPowerUp();
	bool getIsTurnOn(); 

private:
	EventBus* bus;
	bool isTurnOn;
};

#endif  //_SENSORCONTROLLER_H
