//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : Tick.h
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#if !defined(_TICK_H)
#define _TICK_H

#include <thread>
#include <atomic>
#include "SensorController.h"
#include "EventBus.h"

class Tick {
public:
	Tick(EventBus* bus, SensorController* sensor);
	~Tick();
	std::atomic<bool> doCheck;
	void DoDustCheck();
	void StopDustCheck();
	bool getDoCheck();

private:
	std::thread worker;
	SensorController* sensor;
	void Check();
};

#endif  //_TICK_H
