//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : Tick.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#include "Tick.h"

Tick::Tick(EventBus *bus, SensorController *sensor)
{
    bus->subScribeMoveForward([this]() {
            this->DoDustCheck();
        });
    bus->subScribeAvoidObstacle([this](SensorController *sensor) {
        this->StopDustCheck();
        });

    this->sensor = sensor;
}

Tick::~Tick()
{
    StopDustCheck();
}

void Tick::DoDustCheck()
{
    if(doCheck == true) return;

    doCheck = true;
    if(!worker.joinable()){
        worker = std::thread(&Tick::Check, this);
    }
}

void Tick::Check()
{
    while(1){
        if(doCheck == false) break;
        if(sensor){
            sensor->ChecknPowerUp();
        }
        
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
}

void Tick::StopDustCheck() {
    doCheck = false;
    if(worker.joinable()){
        worker.join();
    }
}

bool Tick::getDoCheck()
{
    return doCheck;
}
