//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : Timer.h
//  @ Date : 2026-05-03
//  @ Author : 
//
//

#if !defined(_TIMER_H)
#define _TIMER_H

#include <thread>
#include <functional>
#include <atomic>

class Timer {
public:
	Timer();
	~Timer();
	using ReturnCallback = std::function<void()>;

	void setTimer(int time, ReturnCallback returnCallback );
	void syncTimerDigitalClock();
	int getExpire_Time();	//forTest
	ReturnCallback rc;

private:
	std::atomic<int> Expire_Time = 0;
	
};

#endif  //_TIMER_H
