//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : Timer.h
//  @ Date : 2026-05-03
//  @ Author : 
//
//

#if !defined(_TIMER_H)
#define _TIMER_H

#include <thread>
#include <functional>
#include <atomic>

class Timer {
public:
	Timer();
	~Timer();
	using ReturnCallback = std::function<void()>;

	void setTimer(int time, ReturnCallback returnCallback );
	void doTimer(ReturnCallback returnCallback);
	int getCurrent_Time();	//forTest
	bool getWorkerRunning();	//forTest

private:
	std::thread worker;
	std::atomic<bool> is_running = false;
	std::atomic<int> current_Time = 0;
	
};

#endif  //_TIMER_H
