//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : Timer.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#include "Timer.h"

Timer::Timer() {
    current_Time = 0;
}

Timer::~Timer() {
    if (worker.joinable()) {
        current_Time = 0; // 쓰레드가 loop를 빨리 빠져나오게 유도
        worker.join();    // 쓰레드가 완전히 끝날 때까지 대기
    }
}

void Timer::setTimer(int time, ReturnCallback returnCallback) {
    current_Time = time * 1000;

    if (!is_running) {
        if (worker.joinable()) worker.join(); // 이전 쓰레드 잔해 정리

        is_running = true;
        worker = std::thread(&Timer::doTimer, this, returnCallback);
    }
}

void Timer::doTimer(ReturnCallback returnCallback){
    const int interval = 100; // 50ms    
    while (current_Time > 0) {
        current_Time -= interval;
        std::this_thread::sleep_for(std::chrono::milliseconds(interval));
    }
    is_running = false;

    if (returnCallback) {
        returnCallback();
    } //CleanerController.restore() 사용
}

int Timer::getCurrent_Time()
{
    return current_Time;
}

bool Timer::getWorkerRunning() {
    return is_running;
}

