//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : Timer.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#include "Timer.h"


void Timer::setTimer(int time, ReturnCallback returnCallback) {
    current_Time = time * 1000; // 초를 밀리초로 변환
    if(!worker.joinable()){ //worker 가 살아있다면 갱신
        worker = std::thread(&Timer::doTimer, this, returnCallback);
    }
}

void Timer::doTimer(ReturnCallback returnCallback){
    const int interval = 100; // 100ms    
    while (current_Time > 0) {
        std::this_thread::sleep_for(std::chrono::milliseconds(interval));
        current_Time -= interval;
    }
    returnCallback(); //CleanerController.restore() 사용
}

