//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : MotorController.h
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#if !defined(_MOTOR_H)
#define _MOTOR_H

class Motor {
public:
    virtual ~Motor() = default;

    virtual void stop() {}
    virtual void moveForward() {}
    virtual void turnLeft() {}
    virtual void turnRight() {}
    virtual void moveBackward() {}
};

#endif  //_MOTOR_H
