//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : MotorController.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#include "Motor.h"

void Motor::stop() {}

void Motor::moveForward() {}

void Motor::turnLeft() {}

void Motor::turnRight() {}

void Motor::moveBackward() {}