//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : MotorController.h
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#if !defined(_MOTOR_H)
#define _MOTOR_H

class Point {
public:
    int x;
    int y;

    Point(int x, int y) : x(x), y(y) {}

    bool isEqual(Point other) {
        return this->x == other.x && this->y == other.y;
    }
};

class Motor {
public:
    virtual ~Motor() = default;

    virtual void stop() {}
    virtual void moveForward() {}
    virtual void turnLeft() {}
    virtual void turnRight() {}
    virtual void moveBackward() {}
};

#endif  //_MOTOR_H
