//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : CleanerController.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#include "CleanerController.h"

CleanerController::CleanerController(int EventBus* bus) {

}

void CleanerController::turnOn() {

}

void CleanerController::turnOff() {

}

void CleanerController::CCpowerUp() {

}

void CleanerController::CCpowerRestore() {

}

