//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : CleanerController.h
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#if !defined(_CLEANERCONTROLLER_H)
#define _CLEANERCONTROLLER_H

#include "IPower.h"
#include "EventBus.h"

class CleanerController : public IPower {
public:
	CleanerController(EventBus* bus);
	void turnOn();
	void turnOff();
	void CCpowerUp();
	void CCpowerRestore();
private:
	bool isTurnOn;
	bool powerUp;
};

#endif  //_CLEANERCONTROLLER_H
