//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : CleanerController.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#include "CleanerController.h"
#include "Timer.h"
const int PowerUpDuration = 5000;

CleanerController::CleanerController(EventBus* bus) {
    bus->subScribeMoveForward([this]() {
            this->CCpowerUp();
        });
    Timer timer;
}

void CleanerController::turnOn() {
    isTurnOn = true;
}

void CleanerController::turnOff() {
    isTurnOn = false;
}

void CleanerController::CCpowerUp() {
    //청소기 강하게
    timer.setTimer(PowerUpDuration, [this]() {
            this->CCpowerRestore();
        });
}

void CleanerController::CCpowerRestore() {
    //청소기 원래대로
}

