//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : EventBus.h
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#if !defined(_EVENTBUS_H)
#define _EVENTBUS_H


class EventBus {
public:
	void moveForward();
	void subScribeMoveForward(moveForwardCallBack cb);
	void avoidObstacle(SensorController* sender);
	void subScribeAvoidObstacle(avoidObstacleCallBack cb);
	void HandleDust();
	void subScribeDetectedDust(detectDustCallBack cb);
private:
	vector<moveForwardCallBack> moveForwardSubs;
	vector<avoidObstacleCallBack> avoidObstacleSubs;
	vector<detectDustCallBack> detectDustSubs;
};

#endif  //_EVENTBUS_H
