//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : EventBus.h
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#if !defined(_EVENTBUS_H)
#define _EVENTBUS_H

#include <vector>
#include <functional>
#include "SensorController.h"

class EventBus {
public:
	using moveForwardCallBack = std::function<void()>;
	using avoidObstacleCallBack = std::function<void(SensorController* sender)>;
	using detectDustCallBack = std::function<void()>;
	using turnOffCallBack = std::function<void()>;

	void publishMoveForward();
	void subScribeMoveForward(moveForwardCallBack cb);
	void publishAvoidObstacle(SensorController* sender);
	void subScribeAvoidObstacle(avoidObstacleCallBack cb);
	void publishDetectedDust();
	void subScribeDetectedDust(detectDustCallBack cb);
	void publishTurnOff();
	void subScribeTurnOff(turnOffCallBack cb);

private:
	std::vector<moveForwardCallBack> moveForwardSubs;
	std::vector<avoidObstacleCallBack> avoidObstacleSubs;
	std::vector<detectDustCallBack> detectedDustSubs;
	std::vector<turnOffCallBack> turnOffSubs;
};

#endif  //_EVENTBUS_H
