//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : EventBus.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#include "EventBus.h"

void EventBus::moveForward() {

}

void EventBus::subScribeMoveForward(moveForwardCallBack cb) {

}

void EventBus::avoidObstacle(SensorController* sender) {

}

void EventBus::subScribeAvoidObstacle(avoidObstacleCallBack cb) {

}

void EventBus::HandleDust() {

}

void EventBus::subScribeDetectedDust(detectDustCallBack cb) {

}

