//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : MotorController.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#include "MotorController.h"

MotorController::MotorController(int EventBus* bus) {

}

void MotorController::turnOn() {

}

void MotorController::turnOff() {

}

void MotorController::AvoidObstacle() {

}

void MotorController::MCStop() {

}

void MotorController::MCmoveForward() {

}

void MotorController::MCmoveLeft() {

}

void MotorController::MCmoveRight() {

}

void MotorController::MCmoveBackward() {

}

