//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : MotorController.h
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#if !defined(_MOTORCONTROLLER_H)
#define _MOTORCONTROLLER_H

#include "IPower.h"
#include "SensorProvider.h"
#include "EventBus.h"

class MotorController : public IPower {
public:
	MotorController(EventBus* bus);
	void turnOn();
	void turnOff();
	void AvoidObstacle();
	void MCStop();
private:
	EventBus* bus;
	SensorProvider mySensor;
	bool isTurnOn;
	void MCmoveForward();
	void MCmoveLeft();
	void MCmoveRight();
	void MCmoveBackward();
};

#endif  //_MOTORCONTROLLER_H
