//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : PowerController.h
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#if !defined(_POWERCONTROLLER_H)
#define _POWERCONTROLLER_H


class PowerController {
public:
	void turnOn();
	void turnOff();
private:
	bool power;
};

#endif  //_POWERCONTROLLER_H
