//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : PowerController.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#include "PowerController.h"

void PowerController::turnOn() {

}

void PowerController::turnOff() {

}

