//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : PowerController.h
//  @ Date : 2026-05-03
//  @ Author : 
//
//

#include "EventBus.h"

#if !defined(_POWERCONTROLLER_H)
#define _POWERCONTROLLER_H

class PowerController {
public:
	PowerController(EventBus* bus);
	void turnOn();
	void turnOff();
private:
	bool power;
	EventBus* bus;
};

#endif  //_POWERCONTROLLER_H
