//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : SensorProvider.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#include "SensorProvider.h"

bool SensorProvider::getLeftState() {

}

bool SensorProvider::getRightState() {

}

