//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : SensorProvider.h
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#if !defined(_SENSORPROVIDER_H)
#define _SENSORPROVIDER_H


class SensorProvider {
public:
	virtual bool getLeftState();
	virtual bool getRightState();
};

#endif  //_SENSORPROVIDER_H
