//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : SensorController.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#include "SensorController.h"

SensorController::SensorController(int EventBus* bus) {

}

void SensorController::turnOn() {

}

void SensorController::turnOff() {

}

void SensorController::FrontObstacleDetected() {

}

bool SensorController::getLeftState() {

}

bool SensorController::getRightState() {

}

void SensorController::ChecknPowerUp() {

}

