//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : Tick.cpp
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#include "Tick.h"

void Tick::DoDustCheck() {

}

void Tick::StopDustCheck() {

}

