//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : Tick.h
//  @ Date : 2026-05-03
//  @ Author : 
//
//


#if !defined(_TICK_H)
#define _TICK_H


class Tick {
public:
	bool doCheck;
	void DoDustCheck();
	void StopDustCheck();
private:
	thread worker;
};

#endif  //_TICK_H
