//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OOAD5T
//  @ File Name : Timer.h
//  @ Date : 2026-05-03
//  @ Author : 
//
//

#if !defined(_TIMER_H)
#define _TIMER_H

#include <thread>

class Timer {
public:
	void setTimer();
private:
	std::thread worker;
	float current_Time;
};

#endif  //_TIMER_H
